apiVersion: apps/v1
kind: Deployment
metadata:
  name: prashanthdeployment
  labels:
    app: myapp
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: mynode
        image: prashanth1211/sit323-737-2023-t1-prac5p:latest
        ports:
        - containerPort: 8080